import './globals.css';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={inter.className}>
          <div className='antialiased dark:bg-gray-800 dark:text-gray-100'>
            <div className='flex flex-col min-h-screen space-y-12 mb-auto'>
              <Header />
              <main className='container flex-1 max-w-3xl px-6 mx-auto space-y-12 xl:max-w-5xl'>
                {children}
              </main>
              <Footer />
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
